[window]
width = 1200
height = 900

[files]
resources_path = 'C:\Users\xflajs00\CLionProjects\opengl_template\resources'

[imgui]
path_icons = 'C:\Users\xflajs00\CLionProjects\opengl_template\resources\icons'